spring:
  main:
    allow-circular-references: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        hbm2ddl:
#          auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction:
          jta:
            platform: enable
    hibernate:
      ddl-auto: update #create
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: postgres
    hikari:
      schema: booking_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS booking_schema
      connection-timeout: 10000
